### ISSUE TITLE
Implement persistence.

### ISSUE THREAD

**Issue by rodrigouroz** [scvsoft/temis#11]
Add mongodb and mongoose.
Create a User model and create / update upon authentication.

**Comment by rodrigouroz** [comment]
If we decide to use Mongoose, I'm thinking on creating two models.

- User
- Report

By using population (http://mongoosejs.com/docs/populate.html) we can simulate a one-to-many relationship, storing a User's reference in the Report, just in case we want to filter reports by user in the future (very likely since we don't have all the use cases by now).

User will be populated with profile info from facebook, but I'll abstract the property names just in case we decide to use other authenticator in the future. At a very minimum we need email, display name, age and gender.

I'll leave the Report object simple for now. Just location data (cell location, geo location), title and description. When we implement the report feature we can update this object if needed.

This issue also includes defining the endpoints for creating and retrieving a report (the user creation is done automatically upon authentication if it does not exists).

**Comment by gonrial** [comment]
Remember to include a report.tag element as a way to filter different types of events that are being reported.

**Comment by fa-rodrigouroz** [comment]
Is it a fixed list (enum) or free text?
Multiple tags per report?

**Comment by fa-rodrigouroz** [comment]
No tags for now (as discussed with @gonrial and @holden-caulfield)

**Comment by rodrigouroz** [comment]
No tag field for now (to simplify things), as discussed with @holden-caulfield and @gonrial

**Comment by holden-caulfield** [comment]
By now User and Report LGTM. Next ones should be Alert and Tag, but only when we need them for the corresponding features
