### ISSUE TITLE
Report visualization

### ISSUE THREAD

**Issue by rodrigouroz** [scvsoft/temis#57]
This endpoint summarizes the reports for a given time window and location.

Action: GET /reports/summary

Filters: 

- bounds: minLong, minLat, maxLong, maxLat (a comma separated list in that order)
- radius: radius in KM to build clusters
- startDate (optional)
- endDate (optional)

Example:

GET /reports/summary?bounds=40.714224,-73.961452,50.714224,-77.961452&radius=2

Returns:

```json
{
	"genderStats": {
		"male": 2,
		"female": 3
	},
	"frequencyStats": {
		"frequency": 5,
		"unit": "months"
	},
	"clusters": [{
			"point": [-34.530125, -58.470764],
			"total": 2
		},
		{
			"point": [-34.584779, -58.452485],
			"total": 3
		}
	]
}
```

**Comment by holden-caulfield** [comment]
Minor comment: I would prefer taking a `bounds` parameter that takes a string with something similar to concatenating two `LatLng` Gmaps API parameters 

so For example `bounds=40.714224,-73.961452,50.714224,-77.961452`

**Comment by holden-caulfield** [comment]
LGTM
